######################################################################
# Automatically generated by qmake (2.01a) V júl. 26 02:09:34 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += /home/csmatyas/Aranyositator/. .

# Input
HEADERS += aranyositator.h
SOURCES += aranyositator.cpp main.cpp
