######################################################################
# Automatically generated by qmake (2.01a) P júl. 31 13:16:17 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += arany_scene.h aranyositator.h aranyositator_widget.h
SOURCES += arany_scene.cpp aranyositator.cpp aranyositator_widget.cpp main.cpp
